base_local_planner: "dwa_local_planner/DWAPlannerROS"

TrajectoryPlannerROS:
  acc_lim_x: 0.35
  acc_lim_y: 0.0
  acc_lim_theta: 0.8
  max_vel_x: 1.0
  min_vel_x: 0.15
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_theta: 1.5
  min_vel_theta: -1.5
  min_in_place_vel_theta: 0.3
  holonomic_robot: false
  # base vel/accel profile is in robot folders
  # tolerances (defaults)
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: true
  # forward simulation
  sim_time: 1.0
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  vx_samples: 3
  vtheta_samples: 10
  # scoring (defaults)
  meter_scoring: true
  path_distance_bias: 0.5
  goal_distance_bias: 0.75
  occdist_scale: 0.00625
  heading_lookahead: 0.325
  heading_scoring_timestep: 0.8
  heading_scoring: true
  dwa: false
  # other
  oscillation_reset_dist: 0.05
  # debug
  publish_cost_grid_pc: false

DWAPlannerROS:
  #vel params
  max_vel_x: 0.8 #pioneer max speed
  min_vel_x: 0
  max_trans_vel: 0.8
  min_trans_vel: 0.15
  max_vel_y: 0  #diff drive
  min_vel_y: 0
  max_rot_vel: 5.23599 #300 degrees
  min_rot_vel: 0.4

  #accel params
  acc_lim_x: 2.5
  acc_lim_y: 0  #diff drive
  acc_limit_trans: 2.5
  acc_lim_theta: 8

  #forward sim params
  sim_time: 1.2
  vx_samples: 15
  vy_samples: 1 #diff drive
  vth_samples: 50

  #scoring params
  path_distance_bias: 75
  goal_distance_bias: 60
  occdist_scale: 1.2
  forward_point_distance: 0.3

  #higher goal tolerance
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: true

  #lower goal tolerance
  #yaw_goal_tolerance: 0.05
  #xy_goal_tolerance: 0.1
  #latch_xy_goal_tolerance: false
  
  prune_plan: true
