global_costmap:
  plugins:
  - {name: static_map, type: "costmap_2d::StaticLayer"}
  - {name: 2d_obstacles, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  global_frame: map
  robot_base_frame: pioneer/base_link
  update_frequency: 2.0
  publish_frequency: 10.0
  static_map: 
    map_topic: /map
